[theme]
base = "light"
primaryColor = "#000000"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F7F7"
textColor = "#000000"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
